### PR TITLE
Ihn/update 0.28

### PR DESCRIPTION
**Pull request by ihnorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
Same situation as https://github.com/conda-forge/r-tiledb-feedstock/pull/76#issuecomment-2059472120. You'll need to wait 30-60 minutes for the anaconda.org mirrors to sync and then restart the Azure builds

**Comment by johnkerl** [comment]
@ihnorton CI fail
```
RuntimeError: SHA256 mismatch: 'eba841c56195d02fd190d6d735048f9d187d96bf3e0f7c3c8390036ba8200305' != 'b9be057e0f06bc5692dd1755f6774844e44003234e546e1c1ec82300d6ab7284'
```

**Comment by johnkerl** [comment]
@ihnorton I think

```
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index c9b458d..81d5523 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,6 +1,6 @@
 {% set name = "tiledb" %}
-{% set version = "0.27.1" %}
-{% set sha256 = "b9be057e0f06bc5692dd1755f6774844e44003234e546e1c1ec82300d6ab7284" %}
+{% set version = "0.28.0" %}
+{% set sha256 = "6b1cdc7434886b3db69ba2c3c3a30d5f52c7b27952fac04e3abf7f0b570010db" %}

 package:
   name: tiledb-py
```

but I lack permissions to push a commit here

**Comment by johnkerl** [comment]
... see #209

**Pull request closed without merging**
