### PR TITLE
Bump to 0.32.0

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

I got tired of waiting for the bot to open a PR for 0.32.0. The [GitHub release](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.32.0) happened yesterday as well as a [partial PyPI release](https://pypi.org/project/tiledb/0.32.0/). The source tarball and other wheels were uploaded to PyPI 8 hours ago, and the conda-forge auto-tick bot is [operational](https://github.com/regro/cf-scripts/actions), so I don't know what is causing the delay.

In this PR:

* Also bumped tiledb pin in recipe to 2.26 (you can ignore the 2.25 pins in `.ci_support/` since the recipe pin supersedes them)
* Ensured build number was 0

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]

**Comment by jdblischak** [comment]
Hmmm...I see that we migrated to [numpy 2 for Python >= 3.9](https://github.com/TileDB-Inc/TileDB-Py/blob/0.32.0/pyproject.toml#L9) in https://github.com/TileDB-Inc/TileDB-Py/pull/2036, and the rerendering dropped the py38 build.

Are we ready to migrate the conda recipe to use numpy 2, ie #236?

**Comment by jdblischak** [comment]
I think this should be fine. Even though we haven't migrated VCF to numpy 2 (in progress in https://github.com/TileDB-Inc/TileDB-VCF/pull/762), the run exports when building against numpy 2 is very flexible: `numpy>=1.21,<3`

https://github.com/conda-forge/numpy-feedstock/blob/9f2a921008f6744eb19acbe9306a9e64ff9a925b/recipe/meta.yaml#L6
https://github.com/conda-forge/numpy-feedstock/blob/9f2a921008f6744eb19acbe9306a9e64ff9a925b/recipe/meta.yaml#L51

I confirmed with scipy. scipy 1.13 was transitioned to numpy 2, but I can still install scipy 1.14 with numpy 1:

```sh
# same exact scipy binary can be co-installed with either numpy 1 or 2
mamba create --dry-run -n test-np2 scipy=1.14 numpy=1
##  + numpy                1.26.4  py312heda63a1_0      conda-forge        7MB
##  + scipy                1.14.1  py312h7d485d2_0      conda-forge       18MB

mamba create --dry-run -n test-np2 scipy=1.14 numpy=2
##  + numpy                 2.1.1  py312h58c1407_0      conda-forge        8MB
##  + scipy                1.14.1  py312h7d485d2_0      conda-forge       18MB
```

**Comment by jdblischak** [comment]
I have no idea where the phantom AppVeyor job is coming from. No config file was added, and [AppVeyor has been deprecated](https://conda-forge.org/news/2020/03/23/appveyor-deprecation/) in conda-forge since 2020.

**Comment by jdblischak** [comment]
I asked about the phantom AppVeyor failure in the [conda-forge Gitter](https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$17262377647wlmeE:gitter.im?via=matrix.org&via=gitter.im&via=ifisc.uib-csic.es) and received confirmation that others have seen unexpected AppVeyor notifications. While this is frustrating since it makes it appear something is wrong, this won't actually affect anything.

**Comment by jdblischak** [comment]
CI passed for https://github.com/conda-forge/tiledb-py-feedstock/commit/c43566a2e5873cfee153302f29580c8207acd309 and [0.32.0 binaries](https://anaconda.org/conda-forge/tiledb-py/files?version=0.32.0) were uploaded

**Pull request merged**
